# Generated by Django 6.0.7 on 2026-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(db_index=True, default='legacy_session', max_length=40),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('session_key', 'product'), name='unique_session_product'),
        ),
    ]
